sonar.projectKey=shenam19_myapp
sonar.organization=shenam19
sonar.host.url=https://sonarcloud.io

sonar.language=php
sonar.sources=app
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml

sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**
